//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z_CS_SSP_GET_BP_DETAILS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BPDetailsResponse", Namespace="http://schemas.datacontract.org/2004/07/TNB_SSP.Integration.Z_CS_SSP_GET_BP_DETAI" +
        "LS")]
    public partial class BPDetailsResponse : object
    {
        
        private Z_CS_SSP_GET_BP_DETAILS.BPDetailsResponseBPDetails bPDetailsFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Z_CS_SSP_GET_BP_DETAILS.BPDetailsResponseBPDetails bPDetailsField
        {
            get
            {
                return this.bPDetailsFieldField;
            }
            set
            {
                this.bPDetailsFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BPDetailsResponseBPDetails", Namespace="http://schemas.datacontract.org/2004/07/TNB_SSP.Integration.Z_CS_SSP_GET_BP_DETAI" +
        "LS")]
    public partial class BPDetailsResponseBPDetails : object
    {
        
        private string academicTitleFieldField;
        
        private string bussPartnerCategoryFieldField;
        
        private string bussPartnerLanguageFieldField;
        
        private string bussPartnerNoFieldField;
        
        private string dOBFieldField;
        
        private string firstNameFieldField;
        
        private string formOfAddressKeyFieldField;
        
        private string lastNameFieldField;
        
        private string motherNameFieldField;
        
        private string searchTerm1FieldField;
        
        private string searchTerm2FieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string academicTitleField
        {
            get
            {
                return this.academicTitleFieldField;
            }
            set
            {
                this.academicTitleFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string bussPartnerCategoryField
        {
            get
            {
                return this.bussPartnerCategoryFieldField;
            }
            set
            {
                this.bussPartnerCategoryFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string bussPartnerLanguageField
        {
            get
            {
                return this.bussPartnerLanguageFieldField;
            }
            set
            {
                this.bussPartnerLanguageFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string bussPartnerNoField
        {
            get
            {
                return this.bussPartnerNoFieldField;
            }
            set
            {
                this.bussPartnerNoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string dOBField
        {
            get
            {
                return this.dOBFieldField;
            }
            set
            {
                this.dOBFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firstNameField
        {
            get
            {
                return this.firstNameFieldField;
            }
            set
            {
                this.firstNameFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string formOfAddressKeyField
        {
            get
            {
                return this.formOfAddressKeyFieldField;
            }
            set
            {
                this.formOfAddressKeyFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string lastNameField
        {
            get
            {
                return this.lastNameFieldField;
            }
            set
            {
                this.lastNameFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string motherNameField
        {
            get
            {
                return this.motherNameFieldField;
            }
            set
            {
                this.motherNameFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string searchTerm1Field
        {
            get
            {
                return this.searchTerm1FieldField;
            }
            set
            {
                this.searchTerm1FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string searchTerm2Field
        {
            get
            {
                return this.searchTerm2FieldField;
            }
            set
            {
                this.searchTerm2FieldField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Z_CS_SSP_GET_BP_DETAILS.IZ_CS_SSP_GET_BP_DETAILS")]
    public interface IZ_CS_SSP_GET_BP_DETAILS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZ_CS_SSP_GET_BP_DETAILS/BPDetailsRequest_Out", ReplyAction="http://tempuri.org/IZ_CS_SSP_GET_BP_DETAILS/BPDetailsRequest_OutResponse")]
        System.Threading.Tasks.Task<Z_CS_SSP_GET_BP_DETAILS.BPDetailsResponse> BPDetailsRequest_OutAsync(string contractAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZ_CS_SSP_GET_BP_DETAILS/BPDetailsRequest_Out_ForceCacheRefres" +
            "h", ReplyAction="http://tempuri.org/IZ_CS_SSP_GET_BP_DETAILS/BPDetailsRequest_Out_ForceCacheRefres" +
            "hResponse")]
        System.Threading.Tasks.Task<Z_CS_SSP_GET_BP_DETAILS.BPDetailsResponse> BPDetailsRequest_Out_ForceCacheRefreshAsync(string contractAccount, bool forceCacheRefresh);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IZ_CS_SSP_GET_BP_DETAILSChannel : Z_CS_SSP_GET_BP_DETAILS.IZ_CS_SSP_GET_BP_DETAILS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Z_CS_SSP_GET_BP_DETAILSClient : System.ServiceModel.ClientBase<Z_CS_SSP_GET_BP_DETAILS.IZ_CS_SSP_GET_BP_DETAILS>, Z_CS_SSP_GET_BP_DETAILS.IZ_CS_SSP_GET_BP_DETAILS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Z_CS_SSP_GET_BP_DETAILSClient() : 
                base(Z_CS_SSP_GET_BP_DETAILSClient.GetDefaultBinding(), Z_CS_SSP_GET_BP_DETAILSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IZ_CS_SSP_GET_BP_DETAILS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Z_CS_SSP_GET_BP_DETAILSClient(EndpointConfiguration endpointConfiguration) : 
                base(Z_CS_SSP_GET_BP_DETAILSClient.GetBindingForEndpoint(endpointConfiguration), Z_CS_SSP_GET_BP_DETAILSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Z_CS_SSP_GET_BP_DETAILSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Z_CS_SSP_GET_BP_DETAILSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Z_CS_SSP_GET_BP_DETAILSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Z_CS_SSP_GET_BP_DETAILSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Z_CS_SSP_GET_BP_DETAILSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Z_CS_SSP_GET_BP_DETAILS.BPDetailsResponse> BPDetailsRequest_OutAsync(string contractAccount)
        {
            return base.Channel.BPDetailsRequest_OutAsync(contractAccount);
        }
        
        public System.Threading.Tasks.Task<Z_CS_SSP_GET_BP_DETAILS.BPDetailsResponse> BPDetailsRequest_Out_ForceCacheRefreshAsync(string contractAccount, bool forceCacheRefresh)
        {
            return base.Channel.BPDetailsRequest_Out_ForceCacheRefreshAsync(contractAccount, forceCacheRefresh);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IZ_CS_SSP_GET_BP_DETAILS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IZ_CS_SSP_GET_BP_DETAILS))
            {
                return new System.ServiceModel.EndpointAddress("http://tnbstgmytnbcas1.tnb.my:8012/Inbound/Z_CS_SSP_GET_BP_DETAILS.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Z_CS_SSP_GET_BP_DETAILSClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IZ_CS_SSP_GET_BP_DETAILS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Z_CS_SSP_GET_BP_DETAILSClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IZ_CS_SSP_GET_BP_DETAILS);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IZ_CS_SSP_GET_BP_DETAILS,
        }
    }
}
